In [1]:
lista = [23, 43, 36, 31, 33]

In [2]:
import numpy as np

In [3]:
na = np.array(lista)

In [4]:
print(lista)

[23, 43, 36, 31, 33]


In [5]:
print(na)

[23 43 36 31 33]


In [6]:
type(lista)

list

In [7]:
type(na)

numpy.ndarray

In [8]:
characters = np.array(["aa", 'bb', "cc"])

In [9]:
nb = np.arange(11, 33, 3)

In [10]:
print(nb)

[11 14 17 20 23 26 29 32]


In [15]:
nc = np.zeros(10)

In [12]:
print(nc)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
nd = np.ones(7)

In [16]:
print(nd)

[1. 1. 1. 1. 1. 1. 1.]


In [17]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
lista = [23, 43, 36, 31, 33, 93]
listb = [76, 12, 83, 49, 65, 18]

In [19]:
nd = np.array([lista, listb]) 

In [20]:
np.array([[23, 43, 36, 31, 33, 93], [76, 12, 83, 49, 65, 18]])

array([[23, 43, 36, 31, 33, 93],
       [76, 12, 83, 49, 65, 18]])

In [21]:
nd

array([[23, 43, 36, 31, 33, 93],
       [76, 12, 83, 49, 65, 18]])

In [22]:
print(nd)

[[23 43 36 31 33 93]
 [76 12 83 49 65 18]]


In [23]:
nd.shape

(2, 6)

In [24]:
na.shape

(5,)

In [25]:
na.size

5

In [26]:
nd.size

12

In [27]:
nd.dtype

dtype('int64')

In [28]:
na.dtype

dtype('int64')

In [29]:
nc.dtype

dtype('float64')

In [33]:
ne = np.array([lista, listb], dtype='int8') 

In [34]:
ne.dtype

dtype('int8')

In [35]:
ne.ndim

2

In [36]:
na.ndim

1

In [39]:
listc = [22, 33, 44, 55, 66, 77]

ne = np.array([[lista, listb], [listc, lista]]) 

In [40]:
ne.ndim

3

In [41]:
print(ne)

[[[23 43 36 31 33 93]
  [76 12 83 49 65 18]]

 [[22 33 44 55 66 77]
  [23 43 36 31 33 93]]]


In [42]:
print(nd)

[[23 43 36 31 33 93]
 [76 12 83 49 65 18]]


In [43]:
nd[1][4]

65

In [44]:
ne[1][1][3]

31

In [46]:
np.random.rand(3)

array([0.77142912, 0.00648123, 0.57317676])

In [47]:
np.random.rand(3)

array([0.48753984, 0.03647308, 0.07083205])

In [48]:
np.random.rand(3)

array([0.99401279, 0.11846735, 0.48267314])

In [49]:
np.random.randint(3)

1

In [50]:
np.random.randint(99)

62

In [51]:
np.random.randint(99)

78

In [52]:
np.random.randint(99, size = (5))

array([79, 43, 65, 60, 18])

In [53]:
np.random.randint(99, size = (3, 5))

array([[28,  4, 31, 32, 55],
       [ 3, 86, 43,  5, 84],
       [60, 30, 83,  7, 79]])

In [54]:
np.random.randint(99, size = (3, 5))

array([[22, 77, 79, 70, 13],
       [27, 76,  0, 63, 24],
       [ 1, 44, 14, 43, 23]])

In [55]:
np.random.choice([13, 78, 44, 90, 52])

78

In [56]:
np.random.choice([13, 78, 44, 90, 52])

52

In [57]:
np.random.choice([13, 78, 44, 90, 52])

44

In [58]:
np.random.choice([13, 78, 44, 90, 52], size=(8))

array([90, 44, 78, 78, 90, 78, 78, 13])

In [59]:
np.linspace(0, 4, 6)

array([0. , 0.8, 1.6, 2.4, 3.2, 4. ])

In [60]:
print(nd)

[[23 43 36 31 33 93]
 [76 12 83 49 65 18]]


In [61]:
nd.size

12

In [62]:
nd.reshape(4,3)

array([[23, 43, 36],
       [31, 33, 93],
       [76, 12, 83],
       [49, 65, 18]])

In [63]:
print(nd)

[[23 43 36 31 33 93]
 [76 12 83 49 65 18]]


In [64]:
ng = nd.reshape(3, 4)

In [65]:
ng

array([[23, 43, 36, 31],
       [33, 93, 76, 12],
       [83, 49, 65, 18]])

In [66]:
nh = nd.reshape(6, -1)

In [67]:
print(nh)

[[23 43]
 [36 31]
 [33 93]
 [76 12]
 [83 49]
 [65 18]]


In [68]:
nh = nd.reshape(1, -1)

In [69]:
print(nh)

[[23 43 36 31 33 93 76 12 83 49 65 18]]


In [70]:
nh = nd.reshape(-1, 1)

print(nh)

[[23]
 [43]
 [36]
 [31]
 [33]
 [93]
 [76]
 [12]
 [83]
 [49]
 [65]
 [18]]


In [71]:
print(ng)

[[23 43 36 31]
 [33 93 76 12]
 [83 49 65 18]]


In [72]:
ng.shape

(3, 4)

In [74]:
print(ng[0][1:4])

[43 36 31]


In [75]:
print(ng[:2][1:3])

[[33 93 76 12]]


In [76]:
print(ng[:2, 1:3])

[[43 36]
 [93 76]]


In [78]:
print(ng)
print("-----\n")
print(ng[2])

[[23 43 36 31]
 [33 93 76 12]
 [83 49 65 18]]
-----

[83 49 65 18]


In [79]:
print(ng)
print("-----\n")
print(ng[1:, :2])

[[23 43 36 31]
 [33 93 76 12]
 [83 49 65 18]]
-----

[[33 93]
 [83 49]]


In [80]:
print(nd)

[[23 43 36 31 33 93]
 [76 12 83 49 65 18]]


In [81]:
print(ng)

[[23 43 36 31]
 [33 93 76 12]
 [83 49 65 18]]


In [83]:
nk = np.array([[13, 83, 16, 91],[28, 57, 83, 41], [66, 72, 43, 19]])

In [84]:
print(ng)

[[23 43 36 31]
 [33 93 76 12]
 [83 49 65 18]]


In [85]:
print(nk)

[[13 83 16 91]
 [28 57 83 41]
 [66 72 43 19]]


In [86]:
ng+nk

array([[ 36, 126,  52, 122],
       [ 61, 150, 159,  53],
       [149, 121, 108,  37]])

In [87]:
ng+2

array([[25, 45, 38, 33],
       [35, 95, 78, 14],
       [85, 51, 67, 20]])

In [88]:
ng*2

array([[ 46,  86,  72,  62],
       [ 66, 186, 152,  24],
       [166,  98, 130,  36]])

In [89]:
ng

array([[23, 43, 36, 31],
       [33, 93, 76, 12],
       [83, 49, 65, 18]])

In [90]:
ng-nk

array([[ 10, -40,  20, -60],
       [  5,  36,  -7, -29],
       [ 17, -23,  22,  -1]])

In [92]:
ma = np.array([[1, 0, 2], [4, -2, 3]])
mb = np.array([[4, 0], [2, 3], [1, 4]])

In [93]:
print(ma)
print("\n", mb)

[[ 1  0  2]
 [ 4 -2  3]]

 [[4 0]
 [2 3]
 [1 4]]


In [94]:
ma.dot(mb)

array([[ 6,  8],
       [15,  6]])

In [95]:
print(ng)

[[23 43 36 31]
 [33 93 76 12]
 [83 49 65 18]]


In [96]:
ng.max()

93

In [97]:
ng.min()

12

In [98]:
ng.mean()

46.833333333333336

In [99]:
ng.sum()

562

In [100]:
ng.std()

25.514157290065885

In [101]:
ng.var()

650.9722222222222

In [102]:
np.square(ng)

array([[ 529, 1849, 1296,  961],
       [1089, 8649, 5776,  144],
       [6889, 2401, 4225,  324]])

In [103]:
ni = np.array([9, 16, 81, 27])

In [104]:
np.sqrt(ni)

array([3.        , 4.        , 9.        , 5.19615242])

In [105]:
np.power(ni, 3)

array([   729,   4096, 531441,  19683])

In [107]:
print(ng)
print("\n",ng.transpose())

[[23 43 36 31]
 [33 93 76 12]
 [83 49 65 18]]

 [[23 33 83]
 [43 93 49]
 [36 76 65]
 [31 12 18]]


In [108]:
print(ng)
print("\n",ng.flatten())

[[23 43 36 31]
 [33 93 76 12]
 [83 49 65 18]]

 [23 43 36 31 33 93 76 12 83 49 65 18]


In [111]:
print(ng)
print("\n",ng.flat)

[[23 43 36 31]
 [33 93 76 12]
 [83 49 65 18]]



In [112]:
for i in ng:
    print(i)
    print("----")

[23 43 36 31]
----
[33 93 76 12]
----
[83 49 65 18]
----


In [114]:
for i in ng:
    for j in i:
        print(j)
    print("----")

23
43
36
31
----
33
93
76
12
----
83
49
65
18
----
